controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # You MUST list them here first
    hip_position_controller:
      type: position_controllers/JointGroupPositionController
    osl_hip_position_controller:
      type: position_controllers/JointGroupPositionController
    knee_position_controller:
      type: position_controllers/JointGroupPositionController
    # osl_knee_controller:
    #   type: effort_controllers/JointGroupEffortController
    ankle_position_controller:
      type: position_controllers/JointGroupPositionController
    # osl_ankle_controller:
    #   type: effort_controllers/JointGroupEffortController
    osl_knee_controller:
     type: position_controllers/JointGroupPositionController
    osl_ankle_controller:
     type: position_controllers/JointGroupPositionController


hip_position_controller:
  ros__parameters:
    joints: 
    - hip 

osl_hip_position_controller:
  ros__parameters:
    joints: 
    - osl_hip

knee_position_controller:
  ros__parameters:
    joints: 
    - knee

osl_knee_controller:
  ros__parameters:
    joints: 
    - osl_knee

ankle_position_controller:
  ros__parameters:
    joints: 
    - ankle

osl_ankle_controller:
  ros__parameters:
    joints: 
    - osl_ankle